name: Pull request workflow

on: pull_request

jobs:
    build:
        name: Building, testing and publishing SDK
        runs-on: ubuntu-latest
        env:
            dotnet-version: '6.0'
            build-version: ${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}
        
        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET Core SDK ${{ env.dotnet-version }}
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: ${{ env.dotnet-version }}
            - name: Add nuget sources
              run: dotnet nuget add source --username USERNAME --password ${{ secrets.READ_PACKAGES_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/threesigmaxyz/index.json"
            - name: Install dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --configuration Release --no-restore
            - name: Test
              run: dotnet test --no-restore
            - name: Packaging
              run: dotnet pack --configuration Release --version-suffix "beta${{ env.build-version }}"
            - name: Publish Commons SDK
              run: dotnet nuget push "src/StarkEx.Commons.SDK/bin/Release/*.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
            - name: Publish Crypto SDK
              run: dotnet nuget push "src/StarkEx.Crypto.SDK/bin/Release/*.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
            - name: Publish Client SDK
              run: dotnet nuget push "src/StarkEx.Client.SDK/bin/Release/*.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"